[package]
name = "nim_spice"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
bevy_egui = "0.31.1"

[lib]
name = "nim_spice"
path = "src/lib.rs"
crate-type = ["lib"]

[[bin]]
name = "nim_spice"
path = "src/main.rs"
